name: very_small
type: ddit
# NOTE: governs both the vocab embedding, the rotary embedding, and the transformer block suze
# max in MBBert was 120
hidden_size: 16
# TODO: might need to increase this
cond_dim: 32
# NOTE: this seems to be the text chunk length. Let's try to process the whole image at once
length: 6400
img_size: 80
#NOTE: For MDBert, I used 4 blocks, 8 attention heads
n_blocks: 3
# NOTE: needs to divide hidden_size evenly
n_heads: 4
scale_by_sigma: True
dropout: 0.05
# CNNEmbedder params
# NOTE: set to same as for VI approaches
n_filters: 32
n_cnn_layers: 3